version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    container_name: db_postgres
    env_file:
      - .env 
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net
  
  app:
    build: .
    container_name: app_music
    command: ["/app/docker/app.sh"]
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    networks:
      - app_net  
    env_file:
      - .env       
volumes:
  db-data: 
networks:
  app_net:  